name: Fullstack Deploy

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Poetry (if you use it, else skip)
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back_end/requirements.txt

      - name: Run backend unit tests
        run: |
          cd back_end
          pytest tests/

  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd front_end/react_app
          npm install

      - name: Build frontend
        run: |
          cd front_end/react_app
          npm run build
